<?php
$SetName = array(
    'pay_domain'=>'',
    'epay_pid'=>'',
    'epay_key'=>'',
    'epay_againcheck'=>'0',
    'alipaytype'=>'0',
    'qqpaytype'=>'0',
    'wxpaytype'=>'0',
    'kqxt'=>'1',
    'yjtx'=>'1',
    'alipay_id'=>'',
    'alipay_rsa'=>'',
    'alipay_pkey'=>'',
    'tenpay_id'=>'',
    'qqpay_key'=>'',
    'sitename'=>'温泉PHP网络授权',
    'adminqq'=>'80071319',
    'adminmail'=>'80071319@qq.com',
    'beian'=>'',
    'weburl'=>(((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')) ? 'https://' : 'http://').$_SERVER['SERVER_NAME'].$_SERVER["REQUEST_URI"],
    'smtp_address'=>'',
    'smtp_port'=>'',
    'smtp_user'=>'',
    'smtp_pass'=>'',
    'agentnotice'=>'欢迎使用温泉PHP网络授权系统の代理端，您可以在此充值、自助提卡、开通用户等操作，如有问题请联系本站客服处理。',
    'mainnav'=>'<a class="mdl-navigation__link" href="链接地址1">链接名称1</a> <a class="mdl-navigation__link" href="http://fkw.wenquan6.cn">温泉发卡网</a>',
    'sitekey'=>'',
    'xtsy'=>'1',
    'opencode'=>'false',
    'codevid'=>'',
    'codekey'=>'',
    'maindrawer'=>'',
    'token'=>'',
    'sid'=>'0',
    'stime'=>'0'
);
